### ISSUE TITLE
Location not found on map

### ISSUE THREAD

**Issue by christyleos** [betterangels/buoy#161] opened 2016-09-21 21:29 UTC
- Buoy version: 0.3.2
- Platform: iPhone 9.3.5
- Browser: Safari 
- URL: http://buoyde.vps-1952.devpanel.net/wp-admin/?page=buoy_chat&buoy_hash=58705881ef17c830ce2bbb951c88fb1611e111c908cf5a75c46a08b962c45ace&buoy_nonce=d8051dd44a
- Is it reproducible: Yes
# Steps to Produce/Reproduce
1. Used iPhone to open invite email from team member and it took me to the Buoy Demo registration page where I filled in my personal profile. Location setting notification did not pop up. 
2. Saved Buoy to home screen
3. Created a team and invited 3 people. 
4. Clicked on the plus sign on the top , then Alert, then Buoy icon. 
5. Got safety notification message and closed it. 
6. Took me to message area where I could see responses and send them. 
7. Error message says "emergency alert signal could not be pinpointed on a map"
8. Clicked on map icon and just saw blue screen
9. Clicked on zoom to fit and go to my location, and I get blue screen as well. 
# Expected Results
- For my location to appear on the map so everyone could see it. 
# Actual Results
- Could not find my location on the map.
# Workarounds
- None at this moment

**Comment by fabacab** [comment] 2016-09-21 22:18
This sounds like a duplicate of #157. Remember, for geolocation features to be active on the built-in Safari browser for iPhones, you need to use HTTP_S_, not HTTP. Try doing the same thing but logging into [the HTTPS version of the staging site](https://buoyde.vps-1952.devpanel.net/wp-admin/).

**Comment by christyleos** [comment] 2016-09-21 22:22
![screenshot 176](https://cloud.githubusercontent.com/assets/15221858/18731143/df7bf946-801f-11e6-9842-7e4336d42497.png)

So I got this warning, but I'll log in now.

**Comment by christyleos** [comment] 2016-09-21 22:31
Just did everything you said and it worked. I'd close the issue, but that warning page seems like a problem.

**Comment by fabacab** [comment] 2016-09-21 22:41
Yeah, I mentioned the warning page thing to you [back on Gitter](https://gitter.im/betterangels/buoy?at=57e187eb18291e10488a0d95).

**Closed as completed by fabacab** 2016-09-21 22:41 UTC
Labels: duplicate
