### ISSUE TITLE
Invite emails sent to Crisis Response Team members immediately get routed to Spam folder

### ISSUE THREAD

**Issue by the-phoebe** [betterangels/buoy#225] opened 2017-04-03 04:07 UTC
Invite emails sent to Crisis Response Team members immediately get routed to Spam folder

Buoy version: 0.3.3.
Platform: Mac
Browser: Safari
URL: <img src="http://i346.photobucket.com/albums/p426/pearquero/IMG_4863_zps1shq8cij.png" border="0" alt=" photo IMG_4863_zps1shq8cij.png"/>
Is it reproducible: Yes

# Steps to Produce/Reproduce

1. First step. Add a new member to one of your Crisis Response Teams
1. Second step. Tell individual that you just added to your CRT to look out for the email invite in their inbox 
1. Third step. After several minutes have passed, and the CRT invite email has not shown up, instruct individual to check their Spam folder for it

# Expected Results

Prospective CRT member receives an email notifying them that user would like them to join his CRT

# Actual Results

 The email invite gets routed to prospective CRT member's Spam folder

# Workarounds

<img src="http://i346.photobucket.com/albums/p426/pearquero/IMG_4845_zps3p8uahle.jpg" border="0" alt=" photo IMG_4845_zps3p8uahle.jpg"/>

# Other Information

pearquero@gmail.com holla!

**Comment by christyleos** [comment] 2017-04-03 18:37
@the-phoebe check out issue #34 that might clear the problem up a bit

**Comment by fabacab** [comment] 2017-04-03 19:01
Closing as duplicate of #34.

**Closed as completed by fabacab** 2017-04-03 19:01 UTC
Labels: duplicate
