### ISSUE TITLE
Features 

### ISSUE THREAD

**Issue by ajaypandya1** [betterangels/buoy#134] opened 2016-06-08 08:04 UTC
1)A feature for India would be good is if someone is in trouble one more panic button would raise a LOUD SIREN to catch attention of people near you . In Mumbai city there are many people on the streets but all are busy in their work . India has a population of 1.26 Billion people .

2) A similar Siren can be send to  people"s phone near you through GPS A brief summary of the issue.

**Comment by fabacab** [comment] 2016-06-08 08:06
Duplicate of #10.

**Closed as completed by fabacab** 2016-06-08 08:06 UTC
Labels: duplicate
