### ISSUE TITLE
Dashboard not showing to new users

### ISSUE THREAD

**Issue by ajaypandya1** [betterangels/buoy#167] opened 2016-10-19 16:45 UTC
A brief summary of the issue.
Hello ,
          I as an admin can see Bouy in my admin Dashboard , But my users do not see the Bouy Menus like Great Teams , My Teams etc.

What should I do 
- Buoy version: Latest version
- Platform: Mac / Windows / 
- Browser: Google Chrome / Mozilla Firefox / Internet Explorer
- URL: http://example.com/the_issue_appears_here
- Is it reproducible: Yes / Occasionally / One Time / No
# Steps to Produce/Reproduce
1. First step.
2. Second step.
3. Third step.
4. etc...
# Expected Results

Brief description of what is supposed to happen.
# Actual Results

Brief description of what actually happens. (If an error is shown, be certain to copy-and-paste it here.)
# Workarounds

Brief description of how to avoid the issue or otherwise make due despite it.
# Other Information

Add any other information you believe is pertinent here, such as links to external references, examples in the wild, a way to contact you privately if need be, and so forth.

**Comment by fabacab** [comment] 2016-10-19 16:55
> my users do not see the Bouy Menus like Great Teams , My Teams etc.

Where are they looking?

Users need to log in to the website with their own account first, and then the My Teams, etc. menu will be shown to them in the same place as it is shown to you.

Probably a duplicate of #135.

**Closed as completed by fabacab** 2016-10-19 16:55 UTC
Labels: duplicate

**Comment by ajaypandya1** [comment] 2016-10-25 18:31
I need your help and advise .
1) I have installed a plugin to get a word press dashboard for my users to use BOUY . But my users are not seeing this dashboard . What should I do. They are logged in to the website , but they are not seeing the MY TEAM etc and the dashboard . 

I have installed the below plugin .
Admin Language Per User

|
|
|
|

   |

  |
|  
|   |  
Admin Language Per User
 Switch your backend administration panel in any installed language per user basis.  |   |

  |

  |

 AJAY.

```
On Wednesday, October 19, 2016 12:55 PM, Meitar M. <notifications@github.com> wrote:
```

my users do not see the Bouy Menus like Great Teams , My Teams etc.
Where are they looking?Users need to log in to the website with their own account first, and then the My Teams, etc. menu will be shown to them in the same place as it is shown to you.Probably a duplicate of #135.—

**Comment by fabacab** [comment] 2016-10-25 21:48
> I have installed a plugin to get a word press dashboard for my users to use BOUY .

There is no need to do this. WordPress provides a dashboard by itself.

**Comment by ajaypandya1** [comment] 2016-10-26 15:48
There is no dashboard in their account to create "My Team" for my community users . How can they use BOUY .
Please advise

Sent from Yahoo Mail on Android 

  On Wed, Oct 26, 2016 at 3:18 AM, Meitar M.notifications@github.com wrote:   

I have installed a plugin to get a word press dashboard for my users to use BOUY .

There is no need to do this. WordPress provides a dashboard by itself.
